[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_swap = "FR9rXkzUXvBPEixqo47rasEyiWtRhqSNC5iUxmH4vHHR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/harry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
